surgery_department/urls.py
from django.contrib import admin
from django.urls import path

from surgery_database import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    #general tables
    path('doctors', views.doctors, name='doctors'),
    path('patients', views.patients, name='patients'),
    path('appointments', views.appointments, name='appointments'),
    path('surgeries', views.surgeries, name='surgeries'),
    path('rooms', views.rooms, name='rooms'),
    path('hospitalization', views.hospitalization, name='hospitalization'),

    #doctors
    path('manage_doctor/<doctor_id>/', views.manage_doctor, name='manage_doctor'),
    path('add_doctor', views.add_doctor, name='add_doctor'),
    path('remove_doctor/<doctor_id>/', views.remove_doctor, name='remove_doctor'),

    # stats
    path('doctor_stats', views.doctor_stats, name='doctor_stats'),
    path('doctor_stats_appointments', views.doctor_stats_appointments, name='doctor_stats_appointments'),
    path('specialization_stats', views.specialization_stats, name='specialization_stats'),

    #patients
    path('manage_patient/<patient_id>/', views.manage_patient, name='manage_patient'),
    path('add_patient', views.add_patient, name='add_patient'),
    path('remove_patient/<patient_id>/', views.remove_patient, name='remove_patient'),

    # appointments
    path('manage_appointment/<appointment_id>/', views.manage_appointment, name='manage_appointment'),
    path('create_appointment', views.create_appointment, name='create_appointment'),
    path('remove_appointment/<appointment_id>/', views.remove_appointment, name='remove_appointment'),

    # surgeries
    path('manage_surgery/<surgery_id>/', views.manage_surgery, name='manage_surgery'),
    path('arrange_surgery', views.arrange_surgery, name='arrange_surgery'),
    path('remove_surgery/<surgery_id>/', views.remove_surgery, name='remove_surgery'),

    # rooms
    path('manage_room/<room_number>/', views.manage_room, name='manage_room'),
    path('add_room', views.add_room, name='add_room'),
    path('remove_room/<room_number>/', views.remove_room, name='remove_room'),

    # hospitalization
    path('manage_hospitalization/<hospitalization_id>/', views.manage_hospitalization, name='manage_hospitalization'),
    path('create_hospitalization', views.create_hospitalization, name='create_hospitalization'),
    path('remove_hospitalization/<hospitalization_id>/', views.remove_hospitalization, name='remove_hospitalization'),
    path('check_out_patient/<hospitalization_id>/', views.check_out_patient, name='check_out_patient'),
    path('hospitalize/<patient_id>/', views.hospitalize, name='hospitalize'),

    # documents
    path('medical_record/<patient_id>/', views.medical_record, name='medical_record'),
    path('death_certificate/<patient_id>/', views.death_certificate, name='death_certificate'),
    path('appointment_certificate/<appointment_id>/', views.appointment_certificate, name='appointment_certificate'),
    path('surgery_certificate/<surgery_id>/', views.surgery_certificate, name='surgery_certificate'),
]

surgery_database/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
import datetime


class Appointment(models.Model):
    STATUS_CHOICES = [('P', 'Past'), ('F', 'Forthcoming')]
    appointment_id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey('Patient', db_column='patient_id', on_delete=models.CASCADE, blank=False, null=False)
    doctor_id = models.ForeignKey('Doctor', db_column='doctor_id', on_delete=models.CASCADE, blank=False, null=False)
    appointment_datetime = models.DateTimeField(blank=False, null=False)
    appointment_status = models.CharField(choices=STATUS_CHOICES, max_length=17, default='F', blank=False, null=False)
    diagnosis = models.CharField(max_length=100, blank=True, null=True)
    prescribtion = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'appointments'

    def __str__(self):
        return f"Appointment # {self.appointment_id} made by {self.doctor_id.first_name} {self.doctor_id.last_name} on {self.patient_id.first_name} {self.patient_id.last_name} at {self.appointment_datetime}"


class Doctor(models.Model):
    GENDER_CHOICES = [('F', 'Female'), ('M', 'Male')]
    SPECIALIZATION_CHOICES = [('CR', 'Colon and Rectal Surgery'), ('G', 'General Surgery'), ('T', 'Thoracic Surgery'), ('N', 'Neurological Surgery')]
    doctor_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=70, blank=False, null=False)
    last_name = models.CharField(max_length=70, blank=False, null=False)
    gender = models.CharField(choices= GENDER_CHOICES, max_length=15, blank=False, null=False)
    specialization = models.CharField(choices= SPECIALIZATION_CHOICES, max_length=50, blank=False, null=False)
    email = models.CharField(max_length=50, blank=False, null=False)
    phone = models.IntegerField(blank=False, null=False)
    education = models.CharField(max_length=40, blank=False, null=False)
    experience = models.IntegerField(blank=False, null=False)
    birth_date = models.DateField(blank=False, null=False)
    address = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'doctors'

    def __str__(self):
        return f"{self.first_name} {self.last_name}, {self.specialization}, {self.phone}"


class Hospitalization(models.Model):
    hospitalization_id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey('Patient', db_column='patient_id', on_delete=models.CASCADE, blank=False, null=False)
    check_in_date = models.DateField(default=datetime.date.today, blank=False, null=False)
    check_out_date = models.DateField(blank=True, null=True)
    room_number = models.ForeignKey('Room', on_delete=models.CASCADE, db_column='room_number', blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'hospitalization'

    def __str__(self):
        return f"Hospitalization # {self.hospitalization_id} of {self.patient_id.first_name} {self.patient_id.last_name} on {self.check_in_date} in room {self.room_number.room_number}"


class Patient(models.Model):
    GENDER_CHOICES = [('F', 'Female'), ('M', 'Male')]
    BLOOD_CHOICES = [('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')]
    patient_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=70, blank=False, null=False)
    last_name = models.CharField(max_length=70, blank=False, null=False)
    is_hospitalized = models.BooleanField(default=False, blank=False, null=False)
    gender = models.CharField(choices=GENDER_CHOICES,max_length=17, blank=False, null=False)
    email = models.CharField(max_length=50, blank=False, null=False)
    phone = models.IntegerField(blank=False, null=False)
    address = models.CharField(max_length=100, blank=False, null=False)
    birth_date = models.DateField(blank=False, null=False)
    death_date = models.DateField(blank=True, null=True)
    blood_type = models.CharField(choices=BLOOD_CHOICES, max_length=17, blank=False, null=False)


    class Meta:
        managed = True
        db_table = 'patients'

    def __str__(self):
        return f"{self.first_name} {self.last_name}, {self.address}, {self.phone}"


class Room(models.Model):
    room_number = models.IntegerField(primary_key=True)
    floor = models.IntegerField(blank=False, null=False)
    beds = models.IntegerField(blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'rooms'

    def __str__(self):
        return f"Room number {self.room_number} with {self.beds} on {self.floor} floor"


class Surgery(models.Model):
    STATUS_CHOICES = [('S', 'Successful'), ('U', 'Unsuccessful'), ('F', 'Forthcoming')]
    surgery_id = models.AutoField(primary_key=True)
    appointment_id = models.ForeignKey('Appointment', on_delete=models.CASCADE, db_column='appointment_id', blank=False, null=False)
    surgery_datetime = models.DateTimeField(blank=False, null=False)
    surgery_status = models.CharField(choices=STATUS_CHOICES, max_length=20, blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'surgeries'

    def __str__(self):
        return f"Surgery # {self.surgery_id} made by {self.appointment_id.doctor_id.first_name} {self.appointment_id.doctor_id.last_name} on {self.appointment_id.patient_id.first_name} {self.appointment_id.patient_id.last_name} at {self.surgery_datetime}"

surgery_database/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
from .models import Doctor, Patient, Appointment, Surgery, Room, Hospitalization

class DoctorForm(ModelForm):
    #gender = forms.ChoiceField(choices=Doctor.GENDER_CHOICES)
    class Meta:
        model = Doctor
        fields = ['doctor_id', 'first_name', 'last_name', 'gender', 'specialization', 'email',
                  'phone', 'education', 'experience', 'birth_date', 'address']

        widgets = {
            'gender': forms.Select(choices=Doctor.GENDER_CHOICES),
            'specialization': forms.Select(choices=Doctor.SPECIALIZATION_CHOICES)
        }

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ['patient_id', 'first_name', 'last_name', 'gender', 'blood_type',
                  'phone', 'birth_date', 'death_date', 'address', 'email']

        required = ['patient_id', 'first_name', 'last_name', 'gender', 'blood_type',
                  'phone', 'birth_date', 'address', 'email']

        widgets = {
            'gender': forms.Select(choices=Patient.GENDER_CHOICES),
            'blood_type': forms.Select(choices=Patient.BLOOD_CHOICES),
        }

        labels = {
            'blood_type': _('Blood type'),
        }

class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        fields = ['appointment_id', 'patient_id', 'doctor_id', 'appointment_datetime', 'appointment_status', 'diagnosis',
                  'prescribtion']

        widgets = {
            'patient_id': forms.Select(choices=Patient.objects.all()),
            'appointment_status': forms.Select(choices=Appointment.STATUS_CHOICES),
        }

class SurgeryForm(ModelForm):
    class Meta:
        model = Surgery
        fields = ['appointment_id', 'surgery_id', 'surgery_datetime', 'surgery_status']

        widgets = {
            'appointment_id': forms.Select(choices=Appointment.objects.all()),
            'surgery_status': forms.Select(choices=Surgery.STATUS_CHOICES),
        }

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = ['room_number', 'floor', 'beds']

def not_hospitalized():
    not_hospitalized = []
    result = []
    patients = Patient.objects.all()
    print(patients)
    #hospitalizations = Hospitalization.objects.all()
    for patient in patients:
        hospitalization= Hospitalization.objects.filter(patient_id=patient, check_out_date__isnull=True)
        print('hospitalization', hospitalization)
        if not hospitalization:
            not_hospitalized.append(patient)
    print('NOT', not_hospitalized)

    for patient in not_hospitalized:
        result.append((patient, patient))
    print('RESULT', result)
    return result

class HospitalizationForm(ModelForm):
    class Meta:
        model = Hospitalization
        fields = ['hospitalization_id', 'patient_id', 'check_in_date', 'check_out_date', 'room_number']

        widgets = {
            'patient_id': forms.Select(choices=not_hospitalized()),
        }

surgery_database/templates/add_doctor.html
{% extends "layout.html" %}
{% load static %}


{% block content %}


    <div class="container">

        <form method="post">
        <h3>Add a new doctor</h3>
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

surgery_database/templates/add_patient.html
{% extends "layout.html" %}
{% load static %}


{% block content %}

    <div class="container">
        <form method="post">
        <h3>Add a new patient</h3>
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

surgery_database/templates/add_room.html
{% extends "layout.html" %}
{% load static %}


{% block content %}


    <div class="container">

        <form method="post">
        <h3>Add a new room</h3>
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

surgery_database/templates/arrange_surgery.html
{% extends "layout.html" %}
{% load static %}


{% block content %}
    
    <div class="container">
        <form method="post">
        <h3>Arrange a new surgery</h3>
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>

{% endblock content %}

surgery_database/templates/create_appointment.html
{% extends "layout.html" %}
{% load static %}


{% block content %}
    <div class="container">
        <form method="post">
        <h3>Add a new appointment</h3>
        <p>Notice: after the appointment a patient will be hospitalized </p>
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>

{% endblock content %}

surgery_database/templates/create_hospitalization.html
{% extends "layout.html" %}
{% load static %}


{% block content %}
    
    <div class="container">
        <form method="post">
        <h3>Create a hospitalization</h3>
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>

{% endblock content %}

surgery_database/templates/create_new_appointment.html
{% extends "layout.html" %}
{% load static %}


{% block content %}
    
    <div class="container">
     <div class="row">
            <form class="col s12" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6">
                        <input name="patient_id" id="patient_id" type="text" class="validate">
                        <label for="patient_id">First Name</label>
                    </div>
                    <div class="input-field col s6">
                        <input name="doctor_id" id="doctor_id" type="text" class="validate">
                        <label for="doctor_id">Last Name</label>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s12">
                        <input name="appointment_datetime" id="appointment_datetime" type="text" class="validate">
                        <label for="appointment_datetime">Address </label>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s4">
                        <input name="appointment_status" id="appointment_status" type="text" class="validate">
                        <label for="appointment_status">Country</label>
                    </div>
                </div>
                <hr>
                <div class="right-align total">
                    <button type="submit" class="waves-effect waves-light btn green checkout">Continue</button>
                </div>
             </form>
        </div>


    </div>


{% endblock content %}

surgery_database/templates/doctor_details.html
{% extends "layout.html" %}
{% load static %}


{% block content %}


    <div class="container">

        <form method="post">
            {{ formset }}
        </form>
    </div>

{% endblock content %}

surgery_database/templates/doctor_stats_appointments.html
{% extends "layout.html" %}
{% load static %}


{% block content %}

    <div class="container">
    <h3> Surgeries stats</h3>
     <table id='table' class="responsive-table">
         <thead>
             <tr>
                 <th>#</th>
                 <th>Name</th>
                 <th>Specialization</th>
                 <th>Appointments made</th>
             </tr>
         </thead>

         <tbody>
         {% for doctor, appointments in doctors_stats.items %}
             <tr>
                 <td>{{ doctor.doctor_id }}</td>
                 <td><a href="{%  url 'manage_doctor' doctor.doctor_id %}"> {{ doctor.last_name }} {{ doctor.first_name }}</a></td>
                 <td>{{ doctor.get_specialization_display }}</td>
                 <td>{{ appointments }}</td>

             </tr>

         {% endfor %}

         </tbody>
     </table>
    </div>
{% endblock content %}

surgery_database/templates/manage_appointment.html
{% extends "layout.html" %}
{% load static %}


{% block content %}

    <div class="container">

        <form method="post">
            <h3>Edit an appointment</h3>
            {% csrf_token %}
            {{ form }}

            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>

{% endblock content %}

surgery_database/templates/manage_patient.html
{% extends "layout.html" %}
{% load static %}


{% block content %}


    <div class="container">

        <form method="post">
            <h3>Edit a patient</h3>
            {% csrf_token %}
            {{ form }}

            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>

{% endblock content %}

surgery_database/templates/manage_room.html
{% extends "layout.html" %}
{% load static %}


{% block content %}


    <div class="container">

        <form method="post">
            <h3>Edit a room</h3>
            {% csrf_token %}
            {{ form }}

            <div class="right-align total">
                <button type="submit" class="waves-effect waves-light btn green submit">Submit</button>
            </div>
        </form>
    </div>

{% endblock content %}

surgery_database/templates/patients.html
{% extends "layout.html" %}
{% load static %}
{% load mathfilters %}

{% block content %}

    <div class="tab_container">
        <div class="tab">
            <div id="filter_tab">
                <h5>Filter by:</h5>
                <div class="row">
                    <p><strong>Blood type</strong></p>
                    <p>
                        <label>
                            <input type="checkbox" value="A" class="filled-in myCheckBox">
                            <span>A</span>
                        </label>
                    </p>
                    <p>
                        <label>
                            <input type="checkbox" value="B" class="filled-in myCheckBox">
                            <span>B</span>
                        </label>
                    </p>
                    <p>
                        <label>
                            <input type="checkbox" value="AB" class="filled-in myCheckBox">
                            <span>AB</span>
                        </label>
                    </p>
                    <p>
                        <label>
                            <input type="checkbox" value="O" class="filled-in myCheckBox">
                            <span>O</span>
                        </label>
                    </p>
                </div>

                <button class="waves-effect light-blue btn" onclick="filterByCol(9)">Filter</button>
                <a href="{% url 'patients' %}" class="waves-effect red btn" >Reset</a>
            </div>

            <h5>Sort by:</h5>
            <ul>
                <li><button onclick="sortByText(1)" class="waves-effect grey btn" >name</button></li>
                <li><button onclick="sortByNum(8)" class="waves-effect grey btn">age</button></li>
                <li><button onclick="sortByNum(0)" class="waves-effect grey btn">id</button></li>
            </ul>

        </div>

        <div class="tab_c">
            <div class="inline_buttons">
                <h4>Patients</h4>
                <a class="waves-effect green btn" href="{%  url 'add_patient' %}">Add</a>
            </div>



            <input type="text" id="search_input" placeholder="Search for names.." title="Type in a name">
                <table id='table' class="responsive-table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Gender</th>
                            <th>E-mail</th>
                            <th>Phone</th>
                            <th>Address</th>
                            <th>Date of birth</th>
                            <th>Date of death</th>
                            <th>Age</th>
                            <th>Blood type</th>
                        </tr>
                    </thead>

                    <tbody id="myTable">
                    {% for patient in patients %}
                        <tr>

                            <td>{{ patient.patient_id }}</td>
                            <td><a href="{%  url 'manage_patient' patient.patient_id %}"> {{ patient.last_name }} {{ patient.first_name }}</a></td>
                            <td>{{ patient.get_gender_display }}</td>
                            <td>{{ patient.email }}</td>
                            <td>{{ patient.phone }}</td>
                            <td>{{ patient.address }}</td>
                            <td>{{patient.birth_date }}</td>
                            <td>{% if patient.death_date %} {{ patient.death_date }} {% else %} - {% endif %}</td>
                            <td>
                                {% if patient.death_date %}
                                    {{ patient.death_date|timeuntil:patient.birth_date }}
                                {% else %}
                                    {{ today|timeuntil:patient.birth_date }}
                                {% endif %}
                            </td>
                            <td>{{ patient.get_blood_type_display }}
                            <td><a href="{%  url 'medical_record' patient.patient_id %}">Medical record</a></td>
                            <td>{% if patient.death_date %}<a href="{%  url 'death_certificate' patient.patient_id %}">Death Certificate</a>{% endif %}</td>
                            <td>{% if not patient.is_hospitalized %}<a class="waves-effect blue btn" href="{%  url 'hospitalize' patient.patient_id %}">Hospitalize</a>{% endif %}</td>

                            <td><a href="{% url 'remove_patient' patient.patient_id %}" class="right-align"><i class="fas fa-trash"></i></a></td>
                        </tr>

                    {% endfor %}

                    </tbody>
                </table>
        </div>

    </div>


{% endblock %}

surgery_database/templates/rooms.html
{% extends "layout.html" %}
{% load static %}

{% block content %}

    <div class="tab_container">
        <div class="tab">
            <div id="filter_tab">
                <h5>Filter by:</h5>
                <p>Floor</p>
                <div class="row">
                    <p>
                        <label>
                            <input type="checkbox" value="1"class="filled-in myCheckBox">
                            <span>1</span>
                        </label>
                    </p>
                    <p>
                        <label>
                            <input type="checkbox" value="2" class="filled-in myCheckBox">
                            <span>2</span>
                        </label>
                    </p>
                    <p>
                        <label>
                            <input type="checkbox" value="3" class="filled-in myCheckBox">
                            <span>3</span>
                        </label>
                    </p>
                    <p>
                        <label>
                            <input type="checkbox" value="4" class="filled-in myCheckBox">
                            <span>4</span>
                        </label>
                    </p>
                </div>

                <button onclick="filterByCol(1)" class="waves-effect light-blue btn">Filter</button>
                <a href="{% url 'rooms' %}" class="waves-effect red btn" >Reset</a>
            </div>

            <h5>Sort by:</h5>
            <ul>
                <li><button onclick="sortByNum(0)" class="waves-effect grey btn">room number</button></li>
                <li><button onclick="sortByNum(1)" class="waves-effect grey btn" >floor</button></li>
                <li><button onclick="sortByNum(2)" class="waves-effect grey btn" >beds</button></li>
                <li><button onclick="sortByNum(3)" class="waves-effect grey btn" >vacant places</button></li>
            </ul>

        </div>

        <div class="tab_c">
            <div class="inline_buttons">
                <h4>Rooms</h4>
                <a class="waves-effect green btn" href="{%  url 'add_room' %}">Add a room</a>
            </div>

            <input type="text" id="search_input" placeholder="Search for room numbers.." title="Type in a name">

                <table id='table' class="responsive-table">
                    <thead>
                        <tr>
                            <th>Room number</th>
                            <th>Floor</th>
                            <th>Beds</th>
                            <th>Vacant</th>
                            <th>Patients</th>
                        </tr>
                    </thead>

                    <tbody id="myTable">
                    {% for room in rooms %}
                        <tr>
                            <td><a href="{%  url 'manage_room' room.room_number %}">{{ room.room_number }}</a></td>
                            <td>{{ room.floor }}</td>
                            <td>{{ room.beds }}</td>
                            <td>{{ vacant|get_item:room.room_number }}</td>
                            <td>
                                <ul>
                                {% for hospitalization in hospitalizations %}
                                    {% if hospitalization.room_number == room %}
                                        <li><a href="{%  url 'manage_patient' hospitalization.patient_id.patient_id %}">-{{hospitalization.patient_id.first_name}} {{hospitalization.patient_id.last_name}}, {{hospitalization.patient_id.address}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                </ul>
                            </td>
                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
        </div>

    </div>

{% endblock %}